# Generated by Django 5.2.3 on 2025-06-28 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='from_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_trains', to='trains.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='to_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_trains', to='trains.station'),
        ),
    ]
